import 'package:omega/model/Autogenerated.dart';
import 'package:omega/service/api/notification_api.dart';
import 'package:omega/service/db/dao/notification_dao.dart';
import 'package:omega/service/db/database_provider.dart';
import 'package:omega/service/repository/notification_repository.dart';

class NotificationRepositoryImpl implements NotificationRepository {
  final dao = NotificationDao();
  final api = NotificationApi();

  @override
  DatabaseProvider databaseProvider;

  NotificationRepositoryImpl(this.databaseProvider);

  @override
  Future insert(Notification data) async {

  }

  @override
  Future update(Notification data) {

  }

  @override
  Future delete(Notification data) {

  }

  @override
  Future<Notification> getFromDb() {

  }

  @override
  Future<List<Notification>> getAllFromDb() {

  }
}