import 'package:flutter/material.dart' hide Notification;
import 'package:flutter_html/flutter_html.dart';
import 'package:omega/bloc/notification_bloc.dart';
import 'package:omega/model/Autogenerated.dart';
import 'package:omega/service/db/database_provider.dart';
import 'package:omega/service/repository/notification_repo_implementation.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final bloc = NotificationBloc();
  final repo = NotificationRepositoryImpl(DatabaseProvider.get);

  Future getUpdatedNotifications() async {
    await bloc.updateNotifications();
    final list = await repo.getUnSeen();
    if (list != null && list.isNotEmpty) {
      showNotifications(list);
    }
  }

  showNotifications(List<Notification> list) {
    final size = MediaQuery.of(context).size;
    showDialog(
      context: context,
//      builder: (context) => StatefulBuilder(
      builder: (context) => AlertDialog(
        title: Text(
          'اطلاعیه‌ها',
          textAlign: TextAlign.center,
        ),
        actions: <Widget>[
          FlatButton(
            child: Text(
              'بستن',
              style: TextStyle(color: Colors.red),
            ),
            onPressed: () {
              Navigator.of(context).pop();
            },
          )
        ],
        content: Container(
          height: size.height * (3.0 / 4.0),
          width: size.width * (3.0 / 4.0),
          child: Directionality(
            textDirection: TextDirection.rtl,
            child: ListView.builder(
              itemCount: list.length,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text(list[index].title),
                  subtitle: Html(data: list[index].content),
                );
              },
            ),
          ),
        ),
      ),
//      ),
    ).whenComplete(() {
      bloc.setSeenAll();
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    getUpdatedNotifications();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          //
          //
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have :',
            ),
            Text('Omega Test Project'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  void dispose() {
    bloc.dispose();
    super.dispose();
  }
}
